organigrama/core/urls.py
#Imports Django
from django.conf.urls import url
from django.urls import path
#imports del proyecto
from . import views
from . import autocomplete

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),
]

organigrama/organigrama/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
#Import Extras
import debug_toolbar

#Definimos todas nuestras urls
urlpatterns = [
    #Admin-User Paths
    path('admin/', admin.site.urls),
    #includes
    url(r'^tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    #Proyectos Propios
    path('', include('core.urls')),
    path('organismos/', include('organismos.urls')),
    path('inventario/', include('inventario.urls')),
    path('empleados/', include('empleados.urls')),
]

#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organigrama/core/models.py
from __future__ import unicode_literals
#Imports de la app
from datetime import date
#Imports de Django
from django.db import models
from django.core.files.storage import FileSystemStorage
#Imports extras
from tinymce.models import HTMLField
#Imports del proyecto
from organigrama.settings import MEDIA_URL, LOADDATA
from organigrama.constantes import BEGDA, ENDDA
#Imports de la app
from organismos.choices import JERARQUIA
from empleados.choices import CARGOS

# Create your models here.
class Organismo(models.Model):
    padre = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='hijos')
    nombre = models.CharField('Titulo', max_length=200)
    jerarquia = models.IntegerField(choices=JERARQUIA, default=0)
    descripcion = HTMLField(blank=True, null=True)
    icono = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=200, blank=True, null=True)
    cuit = models.CharField('CUIT', max_length=13, blank=True, null=True)
    telefonos = models.CharField('Telefonos', max_length=100, blank=True, null=True)
    web = models.URLField('Web', blank=True, null=True)
    color = models.CharField(max_length=7, default="#ffffff")
    activo = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    primario = models.BooleanField(default=False)
    def __str__(self):
        if self.padre is not None:
            return self.nombre + ' > ' + self.padre.nombre
        else:
            return self.nombre + ' (Sin Asignar)'
    def as_dict(self):
        if self.padre is None:
            self.padre = self
        return {
            "id": self.id,
            "nombre": self.nombre,
            "padre": self.padre.id,
        }
    def as_full_dict(self):
        return {
            "id": self.id,
            "nombre": self.nombre,
            "descripcion": self.descripcion,
            "icono": self.icono or None,
            "direccion": self.direccion,
            "telefonos": self.telefonos,
            "web": self.web,
        }
    def funcionario_actual(self):
        return self.funcionarios.filter(activo=True)
    def save(self, *args, **kwargs):
        if self.primario == True:
            Organismo.objects.all().exclude(pk=self.id).update(primario=False)
        super(Organismo, self).save(*args, **kwargs)

class Funcionario(models.Model):
    organismo = models.ForeignKey(Organismo, on_delete=models.SET_NULL, related_name='funcionarios', blank=True, null=True)
    cargo = models.IntegerField(choices=CARGOS, default=0)
    subcargo = models.CharField('SubCargo', max_length=20, blank=True, null=True)
    funcion_unica = models.BooleanField(default=False)
    nombres = models.CharField('Nombres', max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    foto = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    dni = models.CharField('DNI', max_length=100, blank=True, null=True)
    titulo = models.CharField('Titulo Profesional', max_length=20)
    email = models.EmailField('Correo Personal', blank=True, null=True)
    telefono = models.CharField('Telefono', max_length=20, blank=True, null=True)
    decreto = models.IntegerField(blank=True, null=True)
    begda = models.DateField('Designacion',  default=BEGDA)
    endda = models.DateField('Cese de Funciones', default=ENDDA)
    activo = models.BooleanField(default=True)
    def __str__(self):
        if self.organismo is None: 
            return 'Sin Organismo > ' + self.nombres + ' ' + self.apellidos
        else:
            return self.organismo.nombre + ' > ' + self.nombres + ' ' + self.apellidos
    def as_dict(self):
        return {
            "organismo": self.organismo.id,
            "nombres": self.nombres,
            "apellidos": self.apellidos,
            "cargo": dict(CARGOS).get(self.cargo),
            "dni": self.dni,
            "foto": self.foto,
            "titulo": self.titulo,
            "email": self.email,
            "telefono": self.telefono,
            "decreto": self.decreto,
        }
    def save(self, *args, **kwargs):
        if self.activo == True and self.funcion_unica:#tener en cuenta otros funcionarios
            self.organismo.funcionarios.exclude(pk=self.pk).filter(cargo=self.cargo,subcargo=self.subcargo).update(endda=self.begda, activo=False)
        super(Funcionario, self).save(*args, **kwargs)

if not LOADDATA:
    from .signals import enviar_mail_new_user

organigrama/core/views.py
#Imports de Python
import json
#Imports de Django
from django.utils import timezone
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
#Import Personales

# Create your views here.
def home(request):
    return render(request, 'home.html', {})

#Manejo de sesiones de Usuarios
def home_login(request):
    message = ''
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return home(request)
    return render(request, "extras/generic_form.html", {'titulo': "Ingresar al Sistema", 'form': form, 'boton': "Ingresar", 'message': message, })

def home_logout(request):
    logout(request)
    return home(request)

organigrama/core/templates/base/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% include 'base/head.html' %}
        {% block custom_css %}
        
        {% endblock %}
    </head>

    {% load custom_tags %}
    <body>
        {% include "base/menu.html" %}
        
        {% block content %}

        {% endblock %}

        {% include "base/footer.html" %}
    </body>
    
    {% include "base/scripts.html" %}
    {% block custom_scripts %}
    
    {% endblock %}
</html>

organigrama/core/templates/base/footer.html
{% load static %}
{% block content %}
      <footer>
        <div class="social">
          <a href="https://www.facebook.com/GobiernoDeJujuy/">
            <span class="icon icon-facebook"></span>
          </a>
          <a href="https://twitter.com/gobiernojujuy">
            <span class="icon icon-twitter"></span>
          </a>
          <a href="https://www.youtube.com/channel/UCJpTTamTMwx0b7zu12M5Y9Q">
            <span class="icon icon-youtube"></span>
          </a>
          <a href="https://www.instagram.com/gobiernodejujuy">
            <span class="icon icon-instagram"></span>
          </a>
        </div>
        
        <div class="row">
          <div class="col-md-2">
            
          </div>
          <div class="col-md-2">
            
          </div>
          <div class="col-md-2" style="float:right;">
            <img class="logo_unif" src="{% static 'img/logo_creador.png' %}" class="logo" style="margin-top: 10px"/>
          </div>
        </div>
      </footer>
{% endblock %}

organigrama/core/templates/base/head.html
{% load static %}

{% block content %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% if refresh %}
        <meta http-equiv="refresh" content="{{refresh}}"/>
    {% endif %}

    <title>{% block title %}Sistema Institucional - Provincia de Jujuy{% endblock %}</title>
    <link rel="icon" href="{% static 'img/icons/favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/screen.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/constantes.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/menu_botones.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/popups.css' %}" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Roboto&display=swap" rel="stylesheet">

    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

    {% if has_table %}
        <!-- Datatables -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/tablas.css' %}" />
    {% endif %}
    
    <!-- Forms -->
    {% if form or has_form %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/generic_form.css" />
        <!-- Date Picker -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.min.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery-ui-1.12.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
    {% endif %}

{% endblock %}

organigrama/core/templates/base/header.html
{% load static %}
{% block content %}
    <div class="portada">
        
    </div>
{% endblock %}

organigrama/core/templates/base/menu.html
{% load static %}
{% block content %}
    <menu>
        <div class="menu-logo">
            <img src="{% static 'img/logo_menu.png' %}" />
        </div>
        <nav class="navbar navbar-static-top">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% include "base/menu_opciones.html" %}
                    </ul>
                </div>
            </div>
        </nav>
    </menu>
{% endblock %}

organigrama/core/templates/base/menu_opciones.html
{% load menu_tags %}

{% block content %}
    <li><a href="{% url 'core:home' %}">Inicio</a></li>
    {% if user.is_authenticated %}
        {% ct_opciones request.user as opciones %}
        <li>
            <a>{{user.username|title}}</a>
            <ul class="submenu">
                {% for opcion in opciones %}
                    <li><a href="/{{opcion.1}}">{{opcion.0}}</a></li>
                {% endfor %}
                {% if user.is_staff %}
                    <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                {% endif %}
                <li><a href="{% url 'core:home_logout' %}">Cerrar Sesion</a></li>
            </ul>
            <span class="triangle glyphicon glyphicon-triangle-bottom"></span>
        </li>
    {% else %}
        <li><a href="{% url 'core:home_login' %}">Ingresar</a></li>
    {% endif %}
{% endblock %}

organigrama/core/templates/base/scripts.html
{% load static %}

{% block content %}
    {% if form %}
        {{ form.media }}
    {% else %}
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    {% endif %}

    {% if has_table %}
        <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/dataTables.buttons.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jszip.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/buttons.html5.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/buttons.print.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/tablescripts.js' %}"></script>
    {% endif %}

    <script type="text/javascript" src="{% static 'js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popups.js' %}"></script>

{% endblock %}