organigrama/core/urls.py
#Imports Django
from django.conf.urls import url
from django.urls import path
#imports del proyecto
from . import views
from . import autocomplete

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),
]

organigrama/organigrama/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
#Import Extras
import debug_toolbar

#Definimos todas nuestras urls
urlpatterns = [
    #Admin-User Paths
    path('admin/', admin.site.urls),
    #includes
    url(r'^tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    #Proyectos Propios
    path('', include('core.urls')),
    path('organismos/', include('organismos.urls')),
    path('inventario/', include('inventario.urls')),
    path('empleados/', include('empleados.urls')),
]

#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organigrama/organismos/urls.py
#Imports Django
from django.conf.urls import url
from django.urls import path
#imports del proyecto
from . import views
from . import autocomplete

app_name = 'organismos'
urlpatterns = [
    #Personales
    path('', views.ministerios, name='ministerios'),
    path('full', views.full_arbol, name='full_arbol'),
    path('<int:origen_id>', views.organismo, name='organismo'),
    path('origen/<int:padre_id>/max/<int:max_child>/', views.org_limit, name='organismos_limit'),
    
    #Generar Listado
    path('lista', views.organismos_listado, name='organismos_pdf'),
    path('lista_edit', views.organismos_listado, name='organismos_pdf'),
    path('simple_list', views.simple_list, name='simple_list'),

    #Edicion
    path('crear_hijo/<int:id_padre>/', views.crear_sub_org, name='crear_sub_org'),
    
    #Autocomplete
    url(r'^organismos-autocomplete/$', autocomplete.OrganismoAutocomplete.as_view(), name='organismos-autocomplete',),

    #Web Services
    path('ws_org/', views.ws_org, name='ws_org'),
    path('ws_org/origen/<int:padre_id>/max/<int:max_child>/', views.ws_org_max, name='ws_org_max'),
    path('ws_organismo/<int:organismo_id>', views.ws_organismo, name='ws_organismo'),
]

organigrama/core/models.py
from __future__ import unicode_literals
#Imports de la app
from datetime import date
#Imports de Django
from django.db import models
from django.core.files.storage import FileSystemStorage
#Imports extras
from tinymce.models import HTMLField
#Imports del proyecto
from organigrama.settings import MEDIA_URL, LOADDATA
from organigrama.constantes import BEGDA, ENDDA
#Imports de la app
from organismos.choices import JERARQUIA
from empleados.choices import CARGOS

# Create your models here.
class Organismo(models.Model):
    padre = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='hijos')
    nombre = models.CharField('Titulo', max_length=200)
    jerarquia = models.IntegerField(choices=JERARQUIA, default=0)
    descripcion = HTMLField(blank=True, null=True)
    icono = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=200, blank=True, null=True)
    cuit = models.CharField('CUIT', max_length=13, blank=True, null=True)
    telefonos = models.CharField('Telefonos', max_length=100, blank=True, null=True)
    web = models.URLField('Web', blank=True, null=True)
    color = models.CharField(max_length=7, default="#ffffff")
    activo = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    primario = models.BooleanField(default=False)
    def __str__(self):
        if self.padre is not None:
            return self.nombre + ' > ' + self.padre.nombre
        else:
            return self.nombre + ' (Sin Asignar)'
    def as_dict(self):
        if self.padre is None:
            self.padre = self
        return {
            "id": self.id,
            "nombre": self.nombre,
            "padre": self.padre.id,
        }
    def as_full_dict(self):
        return {
            "id": self.id,
            "nombre": self.nombre,
            "descripcion": self.descripcion,
            "icono": self.icono or None,
            "direccion": self.direccion,
            "telefonos": self.telefonos,
            "web": self.web,
        }
    def funcionario_actual(self):
        return self.funcionarios.filter(activo=True)
    def save(self, *args, **kwargs):
        if self.primario == True:
            Organismo.objects.all().exclude(pk=self.id).update(primario=False)
        super(Organismo, self).save(*args, **kwargs)

class Funcionario(models.Model):
    organismo = models.ForeignKey(Organismo, on_delete=models.SET_NULL, related_name='funcionarios', blank=True, null=True)
    cargo = models.IntegerField(choices=CARGOS, default=0)
    subcargo = models.CharField('SubCargo', max_length=20, blank=True, null=True)
    funcion_unica = models.BooleanField(default=False)
    nombres = models.CharField('Nombres', max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    foto = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    dni = models.CharField('DNI', max_length=100, blank=True, null=True)
    titulo = models.CharField('Titulo Profesional', max_length=20)
    email = models.EmailField('Correo Personal', blank=True, null=True)
    telefono = models.CharField('Telefono', max_length=20, blank=True, null=True)
    decreto = models.IntegerField(blank=True, null=True)
    begda = models.DateField('Designacion',  default=BEGDA)
    endda = models.DateField('Cese de Funciones', default=ENDDA)
    activo = models.BooleanField(default=True)
    def __str__(self):
        if self.organismo is None: 
            return 'Sin Organismo > ' + self.nombres + ' ' + self.apellidos
        else:
            return self.organismo.nombre + ' > ' + self.nombres + ' ' + self.apellidos
    def as_dict(self):
        return {
            "organismo": self.organismo.id,
            "nombres": self.nombres,
            "apellidos": self.apellidos,
            "cargo": dict(CARGOS).get(self.cargo),
            "dni": self.dni,
            "foto": self.foto,
            "titulo": self.titulo,
            "email": self.email,
            "telefono": self.telefono,
            "decreto": self.decreto,
        }
    def save(self, *args, **kwargs):
        if self.activo == True and self.funcion_unica:#tener en cuenta otros funcionarios
            self.organismo.funcionarios.exclude(pk=self.pk).filter(cargo=self.cargo,subcargo=self.subcargo).update(endda=self.begda, activo=False)
        super(Funcionario, self).save(*args, **kwargs)

if not LOADDATA:
    from .signals import enviar_mail_new_user

organigrama/organismos/models.py
from __future__ import unicode_literals
#Imports de la app
from datetime import date
#Imports de Django
from django.db import models
from django.core.files.storage import FileSystemStorage
#Imports extras
from tinymce.models import HTMLField
from auditlog.registry import auditlog
#Imports del proyecto
from organigrama.settings import MEDIA_URL, LOADDATA
from organigrama.constantes import BEGDA, ENDDA
#Imports de la app
from .choices import JERARQUIA

# Create your models here.
class Organismo(models.Model):
    padre = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='hijos')
    nombre = models.CharField('Titulo', max_length=200)
    jerarquia = models.IntegerField(choices=JERARQUIA, default=0)
    descripcion = HTMLField(blank=True, null=True)
    icono = models.ImageField(storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=200, blank=True, null=True)
    cuit = models.CharField('CUIT', max_length=13, blank=True, null=True)
    telefonos = models.CharField('Telefonos', max_length=100, blank=True, null=True)
    web = models.URLField('Web', blank=True, null=True)
    color = models.CharField(max_length=7, default="#ffffff")
    activo = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    primario = models.BooleanField(default=False)
    def __str__(self):
        if self.padre is not None:
            return self.nombre + ' > ' + self.padre.nombre
        else:
            return self.nombre + ' (Sin Asignar)'
    def as_dict(self):
        if self.padre is None:
            self.padre = self
        return {
            "id": self.id,
            "nombre": self.nombre,
            "padre": self.padre.id,
        }
    def as_full_dict(self):
        return {
            "id": self.id,
            "nombre": self.nombre,
            "descripcion": self.descripcion,
            "icono": self.icono or None,
            "direccion": self.direccion,
            "telefonos": self.telefonos,
            "web": self.web,
        }
    def funcionarios_actuales(self):
        #Obtenemos solo los funcionarios
        funcionarios = self.empleados.exclude(cargo__in=[0, 45,46])#Evitamos los administrativos
        funcionarios = funcionarios.filter(activo=True)
        #Optimizamos
        funcionarios = funcionarios.select_related('individuo')
        return funcionarios
    def save(self, *args, **kwargs):
        if self.primario == True:
            Organismo.objects.all().exclude(pk=self.id).update(primario=False)
        super(Organismo, self).save(*args, **kwargs)

if not LOADDATA:
    #Auditoria
    auditlog.register(Organismo)

organigrama/organismos/views.py
#Imports de Python
import json
#Imports de Django
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.admin.views.decorators import staff_member_required
#Imports del proyecto
#Import Personales
from .models import Organismo
from .functions import calcular_ancho

# Create your views here.
def ministerios(request):
    max_child = 1
    origen = Organismo.objects.filter(primario=True).order_by('id').first()
    ancho = calcular_ancho(origen, max_child)
    return render(request, 'organismos_limit.html', {'origen': origen, 'max_child': max_child, 'ancho': ancho}) 

def full_arbol(request):
    max_child = 50
    origen = Organismo.objects.filter(primario=True).order_by('id').first()
    ancho = calcular_ancho(origen, max_child)
    return render(request, 'organismos.html', {'origen': origen, 'ancho': ancho})

def organismo(request, origen_id):
    max_child = 1
    origen = Organismo.objects.get(id=origen_id, activo=True)
    ancho = calcular_ancho(origen, max_child)
    return render(request, 'organismos_limit.html', {'origen': origen, 'max_child': max_child, 'ancho': ancho}) 

def org_limit(request, padre_id, max_child):
    origen = Organismo.objects.get(id=padre_id)
    ancho = calcular_ancho(origen, max_child)
    return render(request, 'organismos_limit.html', {'origen': origen, 'max_child': max_child, 'ancho': ancho})

def organismos_listado(request):
    origen = Organismo.objects.filter(primario=True).order_by('id').first()
    fecha = timezone.now()
    if request.path_info == "/lista":
        edit = False
    else:
        edit = True
    return render(request, 'lista_organigrama/lista.html', {'origen': origen, 'editable': edit, 'fecha': fecha, })

def simple_list(request):
    origen = Organismo.objects.filter(primario=True).order_by('id').first()
    fecha = timezone.now()
    return render(request, 'lista_organigrama/simple_list.html', {'origen': origen, 'fecha': fecha, })

@staff_member_required
def crear_sub_org(request, id_padre):
    new_org = Organismo()
    new_org.padre = Organismo.objects.get(pk=id_padre)
    new_org.nombre = 'SubOrganismo'
    new_org.save()
    return HttpResponseRedirect('/admin/core/organismo/'+ str(new_org.id) + '/change/')

@staff_member_required
def ws_org(request):
    organismos = [org.as_dict() for org in Organismo.objects.filter(activo=True)]
    return HttpResponse(json.dumps({"data": organismos}), content_type='application/json')

@staff_member_required
def ws_org_max(request, padre_id, max_child):
    organismos = Organismo.objects.none()
    org_buscar = Organismo.objects.filter(id=padre_id)

    for x in range(max_child):
        organismos = organismos | org_buscar
        for org in org_buscar:
            org_buscar = org_buscar.exclude(id=org.id)
            org_buscar = org_buscar | Organismo.objects.filter(padre=org)

    organismos = organismos | org_buscar
    organismos = [org.as_dict() for org in organismos]#Lo convertimos en diccionario serialiable
    return HttpResponse(json.dumps({"data": organismos}), content_type='application/json')

@staff_member_required
def ws_organismo(request, organismo_id):
    organismo = Organismo.objects.get(id=organismo_id).as_full_dict()
    return HttpResponse(json.dumps({"data": organismo}), content_type='application/json')

organigrama/organismos/templates/contacto.html
{% extends 'base_organigrama/base.html' %}

{% block content %}
    <h1>Contacto</h1>
    <hr>
    <ul>
        <li><b>Direccion de Unificacion Informatica</b> [Director: Marcos Federico Mandrille]</li>
        <li><b>Email:</b> <a href="mmandrille@jujuy.gob.ar ">mmandrille@jujuy.gob.ar </a></li>
        <li><b>Dirección:</b> Sarmiento 174, 3E</li>
        <li><b>Telefonico:</b>
            <ul>
                <li>Telefono Fijo: +54 0388 – 4239400</li>
                <li>Whatsapp: +5493884456442</li>
            </ul>
        </li>
    </ul>
{% endblock %}

organigrama/organismos/templates/info_funcionario.html
{% load static %}

{% block content %}
    {% for funcionario in organismo.funcionarios_actuales %}
        <div class="funcionario container">
            <div class="row">
                {% if funcionario.individuo.fotografia %}
                    <div class="col-sm-4">
                            <img src="{{funcionario.individuo.fotografia.url}}" alt="(foto)" class="img_logo">      
                    </div>
                {% endif %}
                <div class="funcionario_info col-sm-8">
                    <p>
                        <b>{{funcionario.get_cargo_display}}:</b> {{funcionario.individuo.titulo}} {{funcionario.individuo.apellidos}}, {{funcionario.individuo.nombres}}
                        {% if editable %}
                            <a class="clean no-print" target="_blank" href="{% url 'admin:organismos_funcionario_change' object_id=funcionario.id %}">
                                <img src="{% static 'img/edit_icon.png' %}" alt="(Edit)" class="icono">
                            </a>
                        {% endif %}
                    </p>
                    <p>{% if funcionario.individuo.telefono %}<b>Telefono:</b>{{funcionario.individuo.telefono}}{%endif%}</p>
                    <p>{% if funcionario.individuo.email %}<b>Email:</b>{{funcionario.individuo.email}}{%endif%}</p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

organigrama/organismos/templates/info_organismo.html
{% load static %}

{% block content %}
    <div class="institucional_titulo">
        <div class="institucional_titulo_texto">
            <h2><a href="{% url 'organismos:organismo' organismo_id=organismo.id %}">{{ organismo.nombre }}</a></h2>
        </div>
        {% if editable %}
            <div class="institucional_titulo_icons no-print">
                <a class="clean" target="_blank" href="{% url 'admin:organismos_organismo_change' object_id=organismo.id %}">
                    <img src="{% static 'img/edit_icon.png' %}" alt="(Edit)" class="icono">
                </a>
                <br>
                <a class="clean" target="_blank" href="{% url 'organismos:crear_sub_org' organismo_id=organismo.id %}">
                    <img src="{% static 'img/add_icon.svg' %}" alt="(Edit)" class="icono">
                </a>
            </div>
        {% endif %}
    </div>
    <div class="institucional_info">
        <h3> Informacion Util:</h3>
        <div id="org{{organismo.id}}_desc" style="display:none;">{{ organismo.descripcion|safe }}</div>
        {% if organismo.direccion %}<p><b>Direccion:</b> {{ organismo.direccion }}</p>{% endif %}
        {% if organismo.telefonos %}<p><b>Telefonos:</b> {{ organismo.telefonos }}</p>{% endif %}
        {% if organismo.web %}<a class="clean no-print" target="_blank" href="{{ organismo.web }}"><b>Pagina Web</b></a>{% endif %}
        {% if organismo.descripcion %}<button onclick="hide_show('org{{organismo.id}}_desc')" class="btn_descripcion no-print">(Ver Descripcion)</button>{% endif %}
    </div>
{% endblock %}

organigrama/organismos/templates/mostrar_organismo.html
{% block content %}
    <div id="{{organismo.id}}" class="popup">
        <a class="organismo">{{ organismo.nombre }}</a>
        <div class="popuptext">
            <div class="tab">
                <button class="tablinks" onclick="openTab(event, 'Organismo-{{organismo.id}}')">Organismo</button>
                <button class="tablinks" onclick="openTab(event, 'Funcionarios-{{organismo.id}}')">Funcionarios</button>
                {% if user.is_staff %}
                    <button class="tablinks" onclick="openTab(event, 'Admin-{{organismo.id}}')">Administracion</button>
                {% endif %}
            </div>

            <div id="Organismo-{{organismo.id}}" class="tabcontent">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            {% if organismo.icono %} 
                                <img class="img_logo" src="{{ organismo.icono.url }}">
                            {% else %}
                                <img class="img_logo" src="/static/img/logo_gobierno.png">
                            {% endif %}
                        </div>
                        <div class="col-sm-8">
                            <div class="clean">
                                <h2 class="nombre_organismo">
                                    <a href="{% url 'organismos:organismo' origen_id=organismo.id %}">
                                        {{ organismo.nombre }}
                                        <img class="img_link" src="/static/img/link.png" alt="ver SubOrganismo">
                                    </a>
                                </h2>
                                {{ organismo.descripcion|safe }}

                                <h3> Informacion Util:</h3>
                                <p><b>Direccion:</b> {{ organismo.direccion }}</p>
                                <p><b>Telefonos:</b> {{ organismo.telefonos }}</p>
                                <a class="clean" target="_blank" href="{{ organismo.web }}"><b>Pagina Web</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div id="Funcionarios-{{organismo.id}}" class="tabcontent" style="display: none;">
                <h2>Funcionarios</h2>
                <div class="funcionarios" style="width: 100%">
                    {% include "info_funcionario.html" with organismo=organismo %}
                </div>
            </div>
            
            <div id="Admin-{{organismo.id}}" class="tabcontent" style="display: none;">
                {% if user.is_staff %}
                    <p class="clean">Modificar organismo o funcionarios</p>
                        <a class="clean" target="_blank" href="{% url 'admin:organismos_organismo_change' object_id=organismo.id %}">
                            <img class="img_icon" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                        </a>
                    </p>
                    
                    <p class="clean">Crear SubOrganismo</p>
                        <a class="clean" target="_blank" href="{% url 'organismos:crear_sub_org' id_padre=organismo.id %}">
                            <img class="img_icon" src="/static/admin/img/icon-addlink.svg" alt="Agregar SubOrganismo">
                        </a>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

organigrama/organismos/templates/nodo_arbol.html
{% block content %}
    <li id="li-{{organismo.id}}">
        {% include "mostrar_organismo.html" with organismo=organismo %}
        {% if organismo.hijos.exists %}
            <ul>
                {% for org_hijo in organismo.hijos.all %}
                    {% include "nodo_arbol.html" with organismo=org_hijo %}
                {% endfor %}
            </ul>
        {% endif %}
    </li>
{% endblock %}

organigrama/organismos/templates/nodo_arbol_limit.html
{% block content %}
    <li id="li-{{organismo.id}}">
        {% include "mostrar_organismo.html" with organismo=organismo %}

        {% if organismo.hijos.exists %}
            {% ifnotequal max_child count  %}
                <ul>
                    {% for org_hijo in organismo.hijos.all %}
                        {% include "nodo_arbol_limit.html" with organismo=org_hijo max_child=max_child count=count|add:1 %}
                    {% endfor %}
                </ul>
            {% endifnotequal %}
        {% endif %}
    </li>
{% endblock %}

organigrama/organismos/templates/organismos.html
{% extends 'base_organigrama/base.html' %}

{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/organigrama.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/pop_up.css' %}" />
{% endblock %}

{% block content %}
    <div class="popup-overlay"></div>
    <div class="organigrama">
        <ul>
            {% include "nodo_arbol.html" with organismo=origen %}
        </ul>
    </div>
{% endblock %}

organigrama/organismos/templates/organismos_limit.html
{% extends 'base_organigrama/base.html' %}

{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/organigrama.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/pop_up.css' %}" />
{% endblock %}

{% block content %}
    <div class="popup-overlay"></div>
    <div class="organigrama">
        <ul>
            {% include "nodo_arbol_limit.html" with organismo=origen max_child=max_child count=0 %}
        </ul>
    </div>
{% endblock %}