organigrama/core/urls.py
#Imports Django
from django.conf.urls import url
from django.urls import path
#imports del proyecto
from . import views
from . import autocomplete

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    #Acceso de usuarios
    path('login', views.home_login, name='home_login'),
    path('logout', views.home_logout, name='home_logout'),
    #Autocomplete
    url(r'^usuarios-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),
]

organigrama/empleados/urls.py
#Imports Django
from django.conf.urls import url
from django.urls import path
#imports del proyecto
from . import views
from . import autocomplete

app_name = 'empleados'
urlpatterns = [
    #Public:
    path('recibo/<int:recibo_id>', views.ver_recibo, name='ver_recibo'),
    #Personales
    path('', views.inicio, name='inicio'),
    
    path('panel/<int:individuo_id>', views.ver_panel, name='ver_panel'),

    path('add/escolaridad/<int:individuo_id>', views.agregar_escolaridad, name='agregar_escolaridad'),
    path('add/habilidad/<int:individuo_id>', views.agregar_habilidad, name='agregar_habilidad'),

    path('mod_datos/<int:individuo_id>', views.DatosBasicosIndividuo, name='mod_datos'),
    path('mod_foto/<int:individuo_id>', views.CambiarFotoIndividuo, name='mod_foto'),

    #Utilidad
    path('buscar/habilidad', views.buscar_por_habilidad, name='buscar_por_habilidad'),

    #Autocomplete
    url(r'^individuos-autocomplete/$', autocomplete.IndividuoAutocomplete.as_view(), name='individuos-autocomplete',),
    url(r'^habilidades-autocomplete/$', autocomplete.TipoHabilidadAutocomplete.as_view(), name='habilidades-autocomplete',),
]

organigrama/organigrama/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
#Import Extras
import debug_toolbar

#Definimos todas nuestras urls
urlpatterns = [
    #Admin-User Paths
    path('admin/', admin.site.urls),
    #includes
    url(r'^tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    #Proyectos Propios
    path('', include('core.urls')),
    path('organismos/', include('organismos.urls')),
    path('inventario/', include('inventario.urls')),
    path('empleados/', include('empleados.urls')),
]

#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organigrama/empleados/models.py
#Imports de python
#Imports django
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
#Imports Extra
from auditlog.registry import auditlog
#Imports del proyecto
from organigrama.settings import LOADDATA
from organigrama.constantes import ENDDA
from core.choices import TIPO_DOCUMENTOS, TIPO_SEXO
from organismos.models import Organismo
#Imports de la app
from .choices import CARGOS, TIPO_RECIBO, NIVEL_EDUCATIVO, NIVEL_HABILIDAD

# Create your models here.
class Individuo(models.Model):
    tipo_doc = models.IntegerField(choices=TIPO_DOCUMENTOS, default=2)
    num_doc = models.CharField('Numero de Documento/Pasaporte', 
        max_length=50,
        validators=[RegexValidator('^[A-Z_\d]*$', 'Solo Mayusculas.')],
        unique=True,
        db_index=True,
    )
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres = models.CharField('Nombres', max_length=100)
    fecha_nacimiento = models.DateField(verbose_name="Fecha de Nacimiento", null=True, blank=True)
    sexo = models.CharField('Sexo', max_length=1, choices=TIPO_SEXO, default='M')
    telefono = models.CharField('Telefono', max_length=50, default='+549388', null=True, blank=True)
    email = models.EmailField('Correo Electronico Personal', null=True, blank=True)
    cuil = models.CharField('CUIL', max_length=13, null=True, blank=True)
    fotografia = models.FileField('Fotografia', upload_to='empleados/individuos/', null=True, blank=True)
    titulo = models.CharField('Titulo Profesional', max_length=50, null=True, blank=True)
    usuario = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="empleado")
    def __str__(self):
        return self.num_doc + ': ' + self.apellidos + ', ' + self.nombres

#Laboral
class Empleo(models.Model):
    organismo = models.ForeignKey(Organismo, on_delete=models.SET_NULL, related_name='empleados', blank=True, null=True)
    individuo = models.ForeignKey(Individuo, on_delete=models.CASCADE, related_name="empleos")
    cargo = models.IntegerField(choices=CARGOS, default=45)
    subcargo = models.CharField('SubCargo', max_length=20, blank=True, null=True)
    decreto = models.IntegerField(blank=True, null=True)
    funcion_unica = models.BooleanField(default=False)
    begda = models.DateField('Designacion',  default=timezone.now)
    endda = models.DateField('Cese de Funciones', default=ENDDA)
    activo = models.BooleanField(default=True)
    #categoria =
    def __str__(self):
        return self.get_cargo_display() + ' en ' + str(self.organismo.nombre)
    def save(self, *args, **kwargs):
        if self.activo == True and self.funcion_unica:#tener en cuenta otros funcionarios
            self.organismo.empleados.exclude(pk=self.pk).filter(cargo=self.cargo,subcargo=self.subcargo).update(endda=self.begda, activo=False)
        super(Empleo, self).save(*args, **kwargs)

class ReciboSueldo(models.Model):
    empleo = models.ForeignKey(Empleo, on_delete=models.CASCADE, related_name="recibos")
    tipo = models.CharField('Tipo Recibo', max_length=3, choices=TIPO_RECIBO, default='REG')
    fecha = models.DateField('Fecha Subido', default=timezone.now)
    archivo = models.FileField('Archivo', upload_to='recibos/')
    aclaracion = models.CharField('Aclaraciones', max_length=1000, blank=True)
    def __str__(self):
        return str(self.empleo) + ' (' + str(self.fecha) + ')'
    def get_pin(self):
        return self.empleo.individuo.num_doc#Se puede determinar otro pin mas eficiente.

#Escolaridad
class Escolaridad(models.Model):
    individuo = models.ForeignKey(Individuo, on_delete=models.CASCADE, related_name='escolaridad')
    nivel = models.IntegerField(choices=NIVEL_EDUCATIVO, default=3)
    titulo = models.CharField('Titulo Profesional', max_length=100)
    establecimiento = models.CharField('Establecimiento Educativo', max_length=100)
    archivo = models.FileField(verbose_name='Archivo', upload_to='personal/escolaridad/', blank=True, null=True)
    begda = models.DateField('Fecha Inicio',  default=timezone.now, blank=True, null=True)
    endda = models.DateField('Fecha Fin', blank=True, null=True)
    terminado = models.BooleanField(default=False)
    def __str__(self):
        if self.terminado:
            tmp = ': Recibido: ' + str(self.endda.month) + '/' + str(self.endda.year)
        else:
            tmp = ': Sin terminar'
        return self.titulo + ' en ' + self.establecimiento + tmp

#Habilidades
class AreaConocimiento(models.Model):
    nombre = models.CharField('Nombres', max_length=100)
    def __str__(self):
        return self.nombre

class TipoHabilidad(models.Model):
    area = models.ForeignKey(AreaConocimiento, on_delete=models.CASCADE, related_name="habilidades")
    nombre = models.CharField('Nombres', max_length=100)
    def __str__(self):
        return self.nombre + ' (' + str(self.area) + ')'

class HabilidadAdquirida(models.Model):
    individuo = models.ForeignKey(Individuo, on_delete=models.CASCADE, related_name='habilidades')
    habilidad = models.ForeignKey(TipoHabilidad, on_delete=models.CASCADE, related_name='habilidades')
    nivel = models.IntegerField(choices=NIVEL_HABILIDAD, default=1)
    descripcion = models.CharField('Descripcion', max_length=200, blank=True, null=True)
    def __str__(self):
        return str(self.habilidad) + ': ' + self.get_nivel_display()

if not LOADDATA:
    #Auditoria
    auditlog.register(Individuo)

    auditlog.register(Empleo)
    auditlog.register(ReciboSueldo)
    auditlog.register(Escolaridad)

    auditlog.register(AreaConocimiento)
    auditlog.register(TipoHabilidad)
    auditlog.register(HabilidadAdquirida)

organigrama/empleados/forms.py
#Imports Django
from django import forms
from django.forms import ModelForm
from django.forms.widgets import TextInput
#Imports Extras
from dal import autocomplete
#Imports del Proyecto
from core.widgets import XDSoftDatePickerInput, XDSoftDateTimePickerInput
#Imports de la app
from .models import Individuo, Empleo
from .models import Escolaridad, HabilidadAdquirida

#Definimos Forms
class Pinform(forms.Form):
    pin = forms.CharField(label='Pin')

class DatosBasicosIndividuoForm(ModelForm):
    class Meta:
        model = Individuo
        fields = (
            'tipo_doc', 'num_doc',
            'apellidos', 'nombres',
            'fecha_nacimiento',
            'sexo',
            'telefono',
            'email',
            'cuil',
            'titulo',
        )
        widgets = {
            'fecha_nacimiento': XDSoftDatePickerInput(attrs={'autocomplete':'off'}),
        }

class FotoIndividuoForm(ModelForm):
    class Meta:
        model = Individuo
        fields = ('fotografia',)

class EmpleoForm(ModelForm):
    class Meta:
        model = Empleo
        fields = '__all__'
        widgets = {
            'organismo': autocomplete.ModelSelect2(url='organismos:organismos-autocomplete'),
        }

class EmpleoOrgForm(ModelForm):
    class Meta:
        model = Empleo
        fields = '__all__'
        widgets = {
            'individuo': autocomplete.ModelSelect2(url='empleados:individuos-autocomplete'),
        }

class EscolaridadForm(ModelForm):
    class Meta:
        model = Escolaridad
        fields = '__all__'
        exclude = ('individuo', )
        widgets = {
            'begda': XDSoftDatePickerInput(attrs={'autocomplete':'off'}),
            'endda': XDSoftDatePickerInput(attrs={'autocomplete':'off'}),
        }

class HabilidadAdquiridaForm(ModelForm):
    class Meta:
        model = HabilidadAdquirida
        fields = '__all__'
        exclude = ('individuo', )
        widgets = {
            'habilidad': autocomplete.ModelSelect2(url='empleados:habilidades-autocomplete'),
        }

organigrama/empleados/views.py
#Imports Django
from django.shortcuts import render, redirect
from django.forms.forms import NON_FIELD_ERRORS
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
#Imports Proyecto
from .functions import get_individuo
from .models import AreaConocimiento, Individuo, ReciboSueldo
from .models import TipoHabilidad, HabilidadAdquirida
from .forms import DatosBasicosIndividuoForm, FotoIndividuoForm
from .forms import EscolaridadForm, HabilidadAdquiridaForm
from .forms import Pinform

# Create your views here.
def inicio(request):
    if request.user.is_staff:
        individuo = get_individuo(request)
        return render(request, 'menu_empleados.html', {
            'individuo': individuo,
        })
    else:
        return redirect('empleados:ver_panel')

def ver_panel(request, individuo_id=None):
    #Buscamos el individuo
    if request.user.is_staff and individuo_id:
        individuo = Individuo.objects.get(pk=individuo_id)
    else:
        individuo = get_individuo(request)
    #Luego de la busqueda
    if individuo:#Si obtuvimos individuo
        #Lanzamos Panel
        return render(request, 'panel_individuo.html', {
            'individuo': individuo,
            }
        )
    else:
        return render(request, 'sin_individuo.html', {})

def ver_recibo(request, recibo_id):
    recibo = ReciboSueldo.objects.get(id=recibo_id)
    form = Pinform()
    if request.method == 'POST':
        form = Pinform(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if pin == recibo.get_pin():
                return redirect(recibo.archivo.url)
            else:
                form.add_error('pin', "El Pin no es Correcto, revise bajo el codigo QR.")#Si esta mal el pin
    #Lanzamos Form
    return render(request, 'extras/generic_form.html', {
        'form': form,
        'titulo': 'Inserte Pin de Seguridad',
        'boton': 'Ingresar'
    })

#Manejo de datos basicos
@login_required
def DatosBasicosIndividuo(request, individuo_id=None):
    individuo = Individuo.objects.get(pk=individuo_id)
    form = DatosBasicosIndividuoForm(instance=individuo)
    if request.method == 'POST':
        form = DatosBasicosIndividuoForm(request.POST, instance=individuo)
        if form.is_valid():
            form.save()#Guardamos los cambios
            return redirect('empleados:ver_panel', individuo_id=individuo.pk)
    return render(request, 'extras/generic_form.html', {'form': form, 'titulo': 'Datos Basicos', 'boton': 'Modificar'})

@login_required
def CambiarFotoIndividuo(request, individuo_id=None):
    individuo = Individuo.objects.get(pk=individuo_id)
    form = FotoIndividuoForm(instance=individuo)
    if request.method == 'POST':
        form = FotoIndividuoForm(request.POST, request.FILES, instance=individuo)
        if form.is_valid():
            form.save()#Guardamos los cambios
            return redirect('empleados:ver_panel', individuo_id=individuo.pk)
    return render(request, 'extras/generic_form.html', {'form': form, 'titulo': 'Fotografia', 'boton': 'Modificar'})

@login_required
def agregar_habilidad(request, individuo_id=None):
    form = HabilidadAdquiridaForm()
    if request.method == 'POST':
        form = HabilidadAdquiridaForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.individuo = Individuo.objects.get(pk=individuo_id)
            form.save()
            return redirect('empleados:ver_panel', individuo_id=form.individuo.pk)
    return render(request, 'extras/generic_form.html', {'form': form, 'titulo': 'Habilidad y Aptitudes', 'boton': 'Agregar'})

@login_required
def agregar_escolaridad(request, individuo_id=None):
    form = EscolaridadForm()
    if request.method == 'POST':
        form = EscolaridadForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.individuo = Individuo.objects.get(pk=individuo_id)
            form.save()
            return redirect('empleados:ver_panel', individuo_id=form.individuo.pk)
    return render(request, 'extras/generic_form.html', {'form': form, 'titulo': 'Historial Academico', 'boton': 'Agregar'})

#Utilidades
@staff_member_required
def buscar_por_habilidad(request):
    if request.method == "GET":
        areas = AreaConocimiento.objects.all()
        return render(request, 'buscar_por_habilidad.html', {
            'areas': areas,
            'has_table': True,
        })
    else:
        #Obtenemos las habilidades seleccionadas
        habilidades_buscadas = [int(id) for id in request.POST.getlist('habilidad')]
        individuos_preseleccionados = Individuo.objects.filter(habilidades__habilidad__in=habilidades_buscadas)#Solo los que tienen esas habilidades
        individuos_preseleccionados = individuos_preseleccionados.distinct()
        #Optimizamos
        individuos_preseleccionados = individuos_preseleccionados.prefetch_related('habilidades')
        #Preparamos la lista a entregar
        individuos = []
        for individuo in individuos_preseleccionados:
            individuo.puntaje = sum([h.nivel for h in individuo.habilidades.all() if h.habilidad.pk in habilidades_buscadas])
            individuos.append(individuo)
        #Ordenamos por fecha
        individuos.sort(key=lambda x: x.puntaje, reverse=True)
        #Lanzamos reporte
        return render(request, 'empleados_por_habilidad.html', {
            'habilidades_buscadas': habilidades_buscadas,
            'individuos': individuos,
        })

organigrama/empleados/templates/buscar_por_habilidad.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Buscar empleado por Habilidades:</h1>
                    <div class="col-md-12">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="listado" id="table">
                                        <thead>
                                            <tr>
                                                <th>Tipo</th>
                                                <th>Nombre</th>
                                                <th>Marcar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for area in areas %}
                                                {% for habilidad in area.habilidades.all %}
                                                    <tr>
                                                        <td>{{area.nombre}}</td>
                                                        <td>{{habilidad.nombre}}</td>
                                                        <td><input type="checkbox" name="habilidad" value="{{habilidad.id}}"></td>
                                                    </tr>
                                                {% endfor %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <br>
                            <div class="row spacer">
                                <div class="col-md-5"></div>
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-block btn-primary">Buscar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

organigrama/empleados/templates/empleados_por_habilidad.html
{% extends 'base/base.html' %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <div class="col-md-12">
                        <h1>Empleados con este Perfil:</h1>
                        {% for individuo in individuos %}
                            <div class="col-md-4">
                                <h3><b>{{individuo.apellidos}}, {{individuo.nombres}}</b></h3>
                                <p>
                                    <b>Puntaje:</b>{{individuo.puntaje}}
                                     <a target="_blank" href="{% url 'empleados:ver_panel' individuo_id=individuo.pk %}">(Ver Resumen)</a>
                                </p>
                                <table class="listado">
                                    <tr>
                                        <th>Habilidad</th>
                                        <th>Nivel</th>
                                    </tr>
                                    {% for habilidad in individuo.habilidades.all %}
                                        <tr {% if habilidad.habilidad.pk in habilidades_buscadas %}style="font-weight: bold;"{% endif %}>
                                            <td>{{habilidad.habilidad.nombre}}</td>
                                            <td>
                                                {{habilidad.get_nivel_display}} ({{habilidad.nivel}})
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

organigrama/empleados/templates/menu_empleados.html
{% extends 'base/base.html' %}

{% load seguridad_tags%}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu Empleados:</h1>
                    <div class="col-md-12">
                        <ul class="menu_botones">
                            {% if individuo %}
                                <li><a href="{% url 'empleados:ver_panel' individuo_id=individuo.pk %}">Ver Mi Panel</a></li>
                            {% endif %}
                            <li><a href="{% url 'admin:empleados_individuo_changelist' %}">Lista Empleados</a></li>
                            <li><a href="{% url 'empleados:buscar_por_habilidad' %}">Buscar Empleados por habilidad</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

organigrama/empleados/templates/panel_individuo.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <br>
                        <div class="row">
                            <div class="col-sm-3">
                                <a href="{% url 'empleados:mod_foto' individuo_id=individuo.id %}" target="_blank">
                                    {% if individuo.fotografia %}
                                        <img class="fotografia" src="{{individuo.fotografia.url}}">
                                    {% else %}
                                        <img class="fotografia" src="{% static '/img/nofoto.png' %}" alt="Modificar">
                                    {% endif %}
                                </a>
                            </div>
                            <div class="col-sm-9">
                                <h2>
                                    <b>{{individuo.apellidos}}, {{individuo.nombres}}</b>
                                    <a href="
                                        {% if user.is_staff %}
                                                {% url 'admin:empleados_individuo_change' object_id=individuo.id %}
                                            {% else %}
                                                {% url 'empleados:mod_datos' individuo_id=individuo.id %}
                                            {% endif %}" 
                                        target="_blank">
                                            <img class="icons" src="{% static '/img/icons/change.png' %}" alt="Modificar">
                                    </a>
                                </h2>
                                <!-- DATOS PERSONALES -->
                                <p><b>Datos Basicos:</b></p>
                                <div class="col-sm-6">
                                    <p>Cuil: {{individuo.cuil}}</p>
                                    <p>Documento: {{individuo.get_tipo_doc_display}} {{individuo.num_doc}}</p>
                                    <p>Fecha de Nacimiento: {{individuo.fecha_nacimiento}}</p>
                                </div>
                                <div class="col-sm-6">
                                    <p><b>Contacto:</b></p>
                                    <p>Telefono: {{individuo.telefono}}</p>
                                    <p>Email: {{individuo.email}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row tab-content">
                    <div class="col-sm-6">
                        <!-- Informacion Academica -->
                        <h2 style="text-align: center;width: 100%;">Escolaridad</h2>
                        <table class="listado">
                            <tr>
                                <th>Nivel</th>
                                <th>Titulo</th>
                                <th>Establecimiento</th>
                                <th>Fechas</th>
                                <th>Documento</th>
                            </tr>
                            {% for registro in individuo.escolaridad.all %}
                                <tr>
                                    <td>{{registro.get_nivel_display}}</td>
                                    <td>{{registro.titulo}}</td>
                                    <td>{{registro.establecimiento}}</td>
                                    <td>{{registro.begda}} - {% if registro.terminado %}{{registro.endda}}{% endif %}</td>
                                    <td>
                                        {% if registro.archivo %}
                                            <a href="{{registro.archivo.url}}">Descargar</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                        <a class="botoncito" href="{% url 'empleados:agregar_escolaridad' individuo_id=individuo.id %}">
                            Agregar Historial Academico
                            <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <!-- Informacion Academica -->
                        <h2 style="text-align: center;width: 100%;">Habilidades y Aptitudes</h2>
                        <table class="listado">
                            <tr>
                                <th>Habilidad</th>
                                <th>Nivel</th>
                                <th>Descripcion</th>
                            </tr>
                            {% for habilidad in individuo.habilidades.all %}
                                <tr>
                                    <td>{{habilidad.habilidad}}</td>
                                    <td>{{habilidad.get_nivel_display}}</td>
                                    <td>{{habilidad.descripcion}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                        <a class="botoncito" href="{% url 'empleados:agregar_habilidad' individuo_id=individuo.id %}">
                            Agregar Habilidad/Aptitud
                            <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
                        </a>
                    </div>
                </div>
                <hr>
                <div class="row tab-content">
                    <!-- Recibos de Sueldo -->
                    <h2>Recibos de Sueldo</h2>
                    {% for empleo in individuo.empleos.all %}
                        <h3>{{empleo}} ({{empleo.begda}} - {{empleo.endda}})</h3>
                        {% for recibo in empleo.recibos.all %}
                            {% if forloop.first %}
                                <table class="listado">
                                    <tr>
                                        <th>Tipo</th>
                                        <th>Fecha</th>
                                        <th>Archivo</th>
                                    </tr>
                            {% endif %}
                            <tr>
                                <td>{{recibo.get_tipo_display}}</td>
                                <td>{{recibo.fecha}}</td>
                                <td>
                                    {% if recibo.archivo %}
                                        <a href="{{recibo.archivo.url}}" target='_blank'>
                                            <img class="icons" src="{% static '/img/icons/download.png' %}" alt="Download">
                                        </a>
                                    {% endif %}
                                </td>
                                <td></td>
                            </tr>
                            {% if forloop.last %}
                                </table>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </div>
            </div>
        </section>
    </section>
{% endblock %}

organigrama/empleados/templates/sin_individuo.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <p>Usted no se encuentra Registrado.</p>
{% endblock %}